import {TOPICS,todayISO,dayNumber,isEligible,statusFor,nextDeadline,matches,toICS} from './rules.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=u=>{try {const parsed=new URL(u);return parsed.protocol==='https:'?esc(parsed.href):'#';}catch{return '#';}};
const dateText=d=>d?d.replaceAll('-','.'):'';
const today=todayISO();
let db={records:[],sources:[],monitor:{}},view='explore',saved=new Set(),toastTimer;
try{const old=JSON.parse(localStorage.getItem('call-atlas-saved')||'[]');if(Array.isArray(old))saved=new Set(old.filter(v=>typeof v==='string'));}catch{}
const params=new URLSearchParams(location.search);
const state={query:params.get('q')||'',publisher:params.get('publisher')||'all',index:params.get('index')||'all',topic:TOPICS.includes(params.get('topic'))?params.get('topic'):'全部方向',status:params.get('status')||'open',sort:params.get('sort')||'deadline'};
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,2800);}
function saveToggle(id){saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('call-atlas-saved',JSON.stringify([...saved]));}catch{toast('当前浏览器无法保存收藏；本次会话仍可使用。');}render();}
function daysBadge(r){const status=statusFor(r,today);if(status==='closed')return '<span class="days-left closed">已截止</span>';if(status==='invitation')return '<span class="days-left urgent">摘要已截止 · 需确认资格</span>';if(status==='review')return '<span class="days-left urgent">信息待复核</span>';if(status==='upcoming')return `<span class="days-left">${dateText(r.submission_opens)} 开始收稿</span>`;const d=nextDeadline(r,today);if(!d)return '<span class="days-left">持续征稿</span>';const n=dayNumber(d)-dayNumber(today),stage=d===r.abstract_deadline?(r.abstract_required===false?'可选摘要':'摘要'):'全文';return `<span class="days-left ${n<=30?'urgent':''}">${stage} · ${n===0?'今日截止':`${n} 天后截止`}</span>`;}
function deadlineBlock(r){return `<div><span class="deadline-label">ABSTRACT DDL${r.abstract_required===false?' · 可选':''}</span><span class="deadline-value ${r.abstract_deadline?'':'unknown'}">${r.abstract_deadline?dateText(r.abstract_deadline):'未单独公布'}</span></div><div><span class="deadline-label">FULL PAPER DDL</span><span class="deadline-value ${r.full_paper_deadline?'':'unknown'}">${r.full_paper_deadline?dateText(r.full_paper_deadline):r.status==='rolling'?'持续征稿':'未公布'}</span><div>${daysBadge(r)}</div></div>`;}
function card(r){const stale=dayNumber(today)-dayNumber(r.checked_at)>7;return `<article class="call-card"><div class="call-body"><div class="journal-line"><span class="publisher-name">${esc(r.publisher)}</span><span class="separator">/</span><span>${esc(r.journal)}</span>${r.indexing.filter(x=>['SSCI','SCIE'].includes(x)).map(i=>`<span class="index-badge">${esc(i)}</span>`).join('')}</div><h3><button class="call-title" data-detail="${esc(r.id)}">${esc(r.title)}</button></h3><p class="call-summary">${esc(r.summary_zh)}</p><div class="call-meta">${r.topics.slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<span class="verified ${stale?'stale':''}">${stale?'◷':'✓'} ${stale?'核验于 '+dateText(r.checked_at):'来源已核验'}</span><button class="bookmark ${saved.has(r.id)?'saved':''}" data-save="${esc(r.id)}" aria-label="${saved.has(r.id)?'取消收藏':'收藏'}：${esc(r.title)}" aria-pressed="${saved.has(r.id)}">${saved.has(r.id)?'★':'☆'}</button></div></div><div class="deadline-panel">${deadlineBlock(r)}</div></article>`;}
function filtered(){let records=db.records.filter(r=>matches(r,state,today));if(view==='saved')records=records.filter(r=>saved.has(r.id));const field=state.sort==='abstract'?'abstract_deadline':'full_paper_deadline';return records.sort((a,b)=>{if(state.sort==='newest')return (b.first_seen||b.checked_at).localeCompare(a.first_seen||a.checked_at)||a.title.localeCompare(b.title);const av=state.sort==='deadline'?nextDeadline(a,today):a[field],bv=state.sort==='deadline'?nextDeadline(b,today):b[field];return (av||'9999').localeCompare(bv||'9999')||a.title.localeCompare(b.title);});}
function updateURL(){const p=new URLSearchParams();for(const [k,v]of Object.entries(state)){if((k==='query'&&v)||(k==='topic'&&v!=='全部方向')||(k==='status'&&v!=='open')||(k==='sort'&&v!=='deadline')||(['publisher','index'].includes(k)&&v!=='all'))p.set(k==='query'?'q':k,v);}if(view!=='explore')p.set('view',view);history.replaceState(null,'',location.pathname+(p.size?'?'+p:'')+location.hash);}
function render(){const records=filtered();$('#saved-count').textContent=db.records.filter(r=>saved.has(r.id)&&isEligible(r,today)).length;$('#result-count').textContent=`${records.length} 条结果`;$('#results-heading').textContent=view==='saved'?'收藏的征稿':'为你收集的征稿';$('#topics').innerHTML=TOPICS.map(t=>`<button class="topic-chip ${state.topic===t?'active':''}" data-topic="${esc(t)}" aria-pressed="${state.topic===t}">${esc(t)}</button>`).join('');const active=state.query||state.publisher!=='all'||state.index!=='all'||state.topic!=='全部方向';$('#active-filters').innerHTML=active?'<div class="filter-note">正在显示筛选结果<button id="reset-filters">清除筛选 ×</button></div>':'';$('#results').innerHTML=records.length?records.map(card).join(''):`<div class="empty"><h3>${view==='saved'?'还没有符合当前筛选的收藏':'没有找到符合条件的征稿'}</h3><p>${view==='saved'?'点击征稿卡片上的星标，即可保存在这个浏览器中。':'试试其他关键词、出版社或截止状态。未核实的收录类别不会显示在这里。'}</p><button class="button" id="empty-reset">清除筛选</button></div>`;if(view==='calendar')renderCalendar(records);updateURL();}
function changeView(v){view=['explore','saved','calendar','sources'].includes(v)?v:'explore';const labels={explore:'发现征稿',saved:'我的收藏',calendar:'截止日期',sources:'来源与核验'};const titles={explore:'让下一篇研究，找到合适的专刊',saved:'值得继续推进的研究机会',calendar:'给下一次投稿，留出时间',sources:'每一条征稿，都有出处'};const subtitles={explore:'汇集出版社官方征稿，按你的研究方向与截止日期筛选。',saved:'收藏保存在当前浏览器；不会上传到 GitHub，也不会跨设备同步。',calendar:'摘要与全文分别列出。导出的日历遵循当前筛选条件。',sources:'仅收录有明确 SSCI / SCIE 依据的期刊，并保留官方链接与核验日期。'};$('#breadcrumb').textContent=labels[view];$('#page-title').innerHTML=esc(titles[view])+'<span>。</span>';$('#page-subtitle').textContent=subtitles[view];$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#listing-section').hidden=['calendar','sources'].includes(view);$('#calendar-section').hidden=view!=='calendar';$('#sources-section').hidden=view!=='sources';$('#controls').hidden=view==='sources';$('#export-ics').hidden=view==='sources';render();}
function renderCalendar(records){const events=records.flatMap(r=>[['abstract_deadline','摘要'],['full_paper_deadline','全文']].filter(([key])=>r[key]&&(state.status!=='open'||r[key]>=today)).map(([key,label])=>({date:r[key],label:label+(key==='abstract_deadline'&&r.abstract_required===false?' · 可选':''),r}))).sort((a,b)=>a.date.localeCompare(b.date));let month='';$('#calendar-section').innerHTML=events.length?events.map(e=>{let head='';if(month!==e.date.slice(0,7)){month=e.date.slice(0,7);head=`<h2 class="calendar-month">${month.slice(0,4)} <span class="muted">年</span> ${Number(month.slice(5))} <span class="muted">月</span></h2>`;}return `${head}<div class="timeline-row"><span class="timeline-date">${e.date.slice(8)}</span><span class="timeline-kind">${e.label}截止</span><div><button class="timeline-title" data-detail="${esc(e.r.id)}">${esc(e.r.title)}</button><small>${esc(e.r.journal)}</small></div></div>`;}).join(''):'<div class="empty"><h3>当前筛选没有明确截止日期</h3><p>持续征稿与未公布日期的专题可在「发现征稿」查看。</p></div>';}
function detail(id){const r=db.records.find(v=>v.id===id);if(!r)return;$('#detail-content').innerHTML=`<div class="eyebrow">${esc(r.publisher)} · SPECIAL ISSUE</div><h2 id="detail-title" class="detail-title">${esc(r.title)}</h2><p class="detail-journal">${esc(r.journal)} ${r.indexing.map(i=>`<span class="index-badge">${esc(i)}</span>`).join(' ')}</p><div class="detail-dates">${deadlineBlock(r)}</div><p class="detail-note">${r.abstract_required===true?'此专题要求先提交摘要；摘要截止后，新作者可能无法进入全文阶段。':r.abstract_required===false?'摘要为可选预审阶段；可直接关注全文截止日期。':r.abstract_deadline?'官方列出了摘要截止，但未明示摘要是否强制。建议在摘要截止前确认；过期后暂停推荐。':'出版社未明确单独摘要阶段；请查看原始征稿要求。'} ${esc(r.deadline_notes_zh||r.deadline_notes||'')}</p><p class="detail-summary">${esc(r.summary_zh)}</p><div class="call-meta">${r.topics.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="detail-actions"><a href="${safeURL(r.cfp_url)}" class="button primary" target="_blank" rel="noopener noreferrer">查看官方征稿 ↗</a><button class="button" data-ics="${esc(r.id)}">加入日历</button><button class="button" data-detail-save="${esc(r.id)}">${saved.has(r.id)?'★ 已收藏':'☆ 收藏专题'}</button></div><div class="detail-evidence">征稿核验：${esc(r.checked_at)}　·　收录核验：${esc(r.indexing_checked_at)}<br>收录依据：<a href="${safeURL(r.indexing_evidence_url)}" target="_blank" rel="noopener noreferrer">期刊官方索引说明 ↗</a>${r.discovery_source_url?`<br>发现入口：<a href="${safeURL(r.discovery_source_url)}" target="_blank" rel="noopener noreferrer">期刊官方征稿页面 ↗</a>`:''}${r.source_format==='external-pdf'?'<br>本条日期来自官网链接的 PDF 人工核验；自动检查可发现新 PDF 链接，受限文档仍需补充核验。':''}${r.issn?`<br>ISSN：${esc(r.issn)}${r.eissn?'　eISSN：'+esc(r.eissn):''}`:''}<br>网站记录的是发现日期，不代表出版社首次发布日。截止日期如未注明时区，请以原文为准。</div>`;$('#detail-dialog').showModal();}
function downloadICS(records){const text=toICS(records,today);if(!text.includes('BEGIN:VEVENT')){toast('当前结果没有可导出的未来截止日期。');return;}const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='call-atlas-deadlines.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('日历已导出，可导入 Google Calendar、Outlook 或 Apple Calendar。');}
function reset(){Object.assign(state,{query:'',publisher:'all',index:'all',topic:'全部方向',status:'open',sort:'deadline'});syncInputs();render();}
function syncInputs(){$('#search').value=state.query;$('#publisher').value=state.publisher;$('#index-filter').value=state.index;$('#status-filter').value=state.status;$('#sort').value=state.sort;}
function journalCoverage(){return `<div class="coverage-heading"><h2>已纳入监测的期刊 <span class="muted">${(db.journal_coverage||[]).length} 本</span></h2><p>点击期刊查看全部征稿，包括已截止记录。入口能读取，不代表每份征稿正文都能读取；页面受限时保留最近一次核验日期。</p></div><div class="coverage-list">${(db.journal_coverage||[]).slice().sort((a,b)=>a.name.localeCompare(b.name)).map(j=>{const calls=db.records.filter(r=>r.journal_id===j.id),open=calls.filter(r=>['open','upcoming'].includes(statusFor(r,today))),reports=(db.monitor?.sources||[]).filter(s=>j.source_ids.includes(s.id)),readable=calls.filter(r=>(db.monitor?.pages||[]).some(p=>p.url.replace(/\/$/,'')===r.cfp_url.replace(/\/$/,'')&&p.status==='ok')).length;return `<article class="coverage-row"><div><a class="coverage-name" href="?q=${encodeURIComponent(j.name)}&status=all">${esc(j.name)} ↗</a><p>${esc(j.publisher)} · ${j.indexing.map(esc).join(' / ')} · 收录核验 ${esc(j.checked_at)}</p></div><div class="coverage-count"><strong>${open.length} 条可规划</strong><span>${calls.length} 条记录</span><small>${reports.length?reports.some(r=>r.status==='ok')?'入口可读':'自动读取受限':'等待自动检查'}${calls.length?` · 正文 ${readable}/${calls.length} 可读`:''}</small></div></article>`;}).join('')}</div>`;}
function sources(){const mon=db.monitor||{};$('#sources-section').innerHTML=`${journalCoverage()}<h2 style="margin-top:30px">严格收录，透明覆盖</h2><p class="source-intro">本网站关注 AI、NLP、可解释 AI、教育技术、教育学、心理学、STEM 与语言教育。SCI 按 Web of Science 的 SCIE 口径处理；ESCI、Scopus 和影响因子本身均不能作为通过依据。<br>目前采用已核实期刊与配置的官方入口进行发现。各出版社网页结构、登录与反爬限制不同，不能保证全网零遗漏；访问失败会保留记录，不会被当作「没有新征稿」。</p><div class="notice">${mon.last_run?`最近自动检查：${esc(mon.last_run)}。成功读取 ${Number(mon.succeeded)||0} 个页面，${Number(mon.failed)||0} 个页面未能读取。`:'自动检查尚未完成首轮运行；当前为人工核验的初始清单。'} 索引证据每次扫描尝试更新，超过 90 天未能复核的期刊将退出展示和推送。征稿页面超过 7 天未确认则暂停通知。</div><div class="source-grid">${(db.sources||[]).map(s=>{const report=(mon.sources||[]).find(v=>v.id===s.id);return `<article class="source-box"><h3>${esc(s.publisher)}</h3><p>${esc(s.description||'通过出版社官方专题与期刊征稿入口发现新征稿。')}</p><a href="${safeURL(s.url)}" target="_blank" rel="noopener noreferrer">官方征稿入口 ↗</a><div class="source-status ${report&&report.status!=='ok'?'failed':''}">${report?report.status==='ok'?`最近读取成功 · 发现 ${report.candidates||0} 个候选链接`:'最近读取受限 · 需要补充核验':'等待首轮自动检查'}</div></article>`;}).join('')}</div><h2 style="margin-top:30px">推送规则</h2><ol class="method-list"><li>从出版社与独立期刊的官方入口发现专题；官网外链 PDF 保留来源关系，受限文档进入待核验清单。</li><li>期刊必须有明确、有效的 SSCI 或 SCIE 收录证据；未核实的候选不进入 RSS 或 GitHub 通知。</li><li>摘要与全文日期分别提取。日期冲突、年份不明或需要人工解释的记录暂停推送。</li><li>新增、截止日期变更，以及 30 / 14 / 7 天内临近截止可触发一次通知。GitHub 通知通过 Issues 订阅接收。</li><li>跨刊专题按具体期刊区分。仅属于 ESCI 的参与刊物不会因共享专题而被放行。</li></ol><a class="text-link" href="https://mjl.clarivate.com/home" target="_blank" rel="noopener noreferrer">在 Clarivate Master Journal List 进一步核对 ↗</a>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)changeView(b.dataset.view);else if(b.dataset.topic){state.topic=b.dataset.topic;render();}else if(b.dataset.detail)detail(b.dataset.detail);else if(b.dataset.save)saveToggle(b.dataset.save);else if(b.dataset.detailSave){saveToggle(b.dataset.detailSave);b.textContent=saved.has(b.dataset.detailSave)?'★ 已收藏':'☆ 收藏专题';}else if(b.dataset.ics)downloadICS(db.records.filter(r=>r.id===b.dataset.ics));else if(b.hasAttribute('data-close'))b.closest('dialog').close();else if(['reset-filters','empty-reset'].includes(b.id))reset();});
$('#search').addEventListener('input',e=>{state.query=e.target.value;render();});
for(const [id,key]of [['publisher','publisher'],['index-filter','index'],['status-filter','status'],['sort','sort']])$('#'+id).addEventListener('change',e=>{state[key]=e.target.value;render();});
$('#export-ics').onclick=()=>downloadICS(filtered());$('#subscribe-top').onclick=()=>$('#subscribe-dialog').showModal();$('#method-button').onclick=()=>{changeView('sources');window.scrollTo({top:0,behavior:'smooth'});};
$('#copy-rss').onclick=async()=>{try{await navigator.clipboard.writeText($('#rss-url').value);toast('已复制 RSS 订阅地址。');}catch{$('#rss-url').focus();$('#rss-url').select();toast('请复制选中的订阅地址。');}};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('dialog[open]')){e.preventDefault();if(view==='sources')changeView('explore');$('#search').focus();}});
async function init(){try{const response=await fetch('data.json',{cache:'no-cache'});if(!response.ok)throw new Error('数据读取失败');db=await response.json();const eligible=db.records.filter(r=>isEligible(r,today)),open=eligible.filter(r=>['open','upcoming'].includes(statusFor(r,today)));$('#stat-open').textContent=open.length;$('#nav-count').textContent=open.length;$('#stat-soon').textContent=open.filter(r=>{const d=nextDeadline(r,today);return d&&dayNumber(d)-dayNumber(today)<=30;}).length;$('#stat-journals').textContent=(db.journal_coverage||[]).length||new Set(open.map(r=>r.journal)).size;$('#stat-updated').textContent=dateText(db.updated_at?.includes('T')?new Intl.DateTimeFormat('sv-SE',{timeZone:'America/New_York'}).format(new Date(db.updated_at)):db.updated_at||'');$('#stat-updated-note').textContent=db.monitor?.last_run?'自动检查 + 官方证据':'初始数据人工核验';$('#sidebar-status').textContent=db.monitor?.last_run?'每日检查已运行':'初始数据已核验';$('#today').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',timeZone:'America/New_York'}).format(new Date());$('#publisher').innerHTML='<option value="all">所有出版社</option>'+[...new Set([...(db.sources||[]).map(s=>s.publisher),...db.records.map(r=>r.publisher)])].sort().map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');if(!$('#publisher').querySelector(`option[value="${CSS.escape(state.publisher)}"]`))state.publisher='all';if(!['all','SSCI','SCIE'].includes(state.index))state.index='all';if(!['open','all','closed'].includes(state.status))state.status='open';if(!['deadline','newest','abstract','full'].includes(state.sort))state.sort='deadline';$('#rss-url').value=new URL('feed.xml',location.href).href;sources();syncInputs();changeView(params.get('view')||'explore');if(db.monitor?.last_run)$('#subscription-status').textContent=`最近自动检查：${db.monitor.last_run}。GitHub Actions 每日运行；仅在有可推送变化时发通知。`;}catch(err){$('#results').innerHTML='<div class="error-banner">数据暂时无法读取。请刷新页面，或通过 GitHub 项目检查数据更新状态。</div>';$('#sidebar-status').textContent='数据读取失败';console.error(err);}}
init();
